Protect against failed cast
next-exp/nexus pull request #162
Opened 2022-04-21 17:07 UTC by gondiaz

In interactive mode, you might want to use **DefaultEventAction** without **DefaultTrackingAction**. Since you are in interactive mode, Geant4 will provide a not empty `G4TrajectoryContainer`, which is a vector of `G4VTrajectory`. The dowcast fails since `Trajectory` is a nexus class.

2022-04-21 17:17 UTC, paolafer commented
I would say that in the interactive mode there is no need to use `DefaultEventAction` either, since one is not concerned with how many events are saved in the output file. One could simply use the default actions by not specifying any custom actions.
In fact, if one wanted to save only events with energy deposition above a threshold, and at the same time is not using `DefaultTrackingAction`, it wouldn't work, because the calculated energy deposited would be always zero.  I will document the use of each action better, once the PR on the clean-up of the actions is approved.

2022-04-21 17:28 UTC, paolafer commented
What we could do is, instead of adding a protection, adding a meaningful error message and let the program crash.

2022-04-22 07:57 UTC, gondiaz commented
Agree. What do you think about placing such an error before the `SetUserAction` in `NexusApp.cc`? This would assure that you always choose a compatible set of user actions

2022-04-27 08:51 UTC, paolafer commented
> Agree. What do you think about placing such an error before the `SetUserAction` in `NexusApp.cc`?

I don't like it vey much, I would prefer to keep the code in the  `NexusApp` class as simple as possible. I would rather put the protection in `DefaultEventAction`, which is the class that accesses the `Trajectory object`.

2022-07-26 11:06 UTC, paolafer commented
@gondiaz, what about this PR? Are you going to add the comment to the crash or shall we close it?

2022-07-26 20:54 UTC, gondiaz commented
At least not in the next two weeks

2022-07-26 20:59 UTC, paolafer commented
> At least not in the next two weeks

This doesn't answer my question :-).

2022-07-26 21:08 UTC, gondiaz commented
The answer is yes then, but I don't know when. 
If it is annoying to have this pending, it can be closed. If anyone wants to contribute and finish it, also works for me.

2022-07-26 21:12 UTC, paolafer commented
It's not annoying, I just want to know if you forgot about it or you are going to finish it at some point.

2022-08-10 13:43 UTC, paolafer requested changes

2022-08-10 13:43 UTC, paolafer commented on source/actions/DefaultEventAction.cc
> +          G4Exception("[DefaultEventAction]", "EndOfEventAction", FatalException,
In the nexus convention, the second argument of `G4Exception` should be the function, so `()` should be added.

2022-08-10 13:43 UTC, paolafer commented on source/actions/DefaultEventAction.cc
> +                      "Adequate TrackingAction not registered for DefaultEventAction");
I would say explicitly which one is the correct action, something like "DefaultTrackingAction is required when using DefaultEventAction".

2022-08-11 06:57 UTC, paolafer approved these changes
This PR adds a useful error message when `DefaultTrackingAction` is not used together with `DefaultEventAction`. Approved!

2022-08-11 06:57 UTC, merged