Polygon sampler
next-exp/nexus pull request #249
Opened 2024-02-27 05:22 UTC by kvjmistry

This PR adds the option of generating events in a polygon with n sides. This is useful for generating in geometries such as the light tube. As an example I have used this generator as the default in DEMO.

The plots below show generation of Kr83 events in the INSIDE (gas), VOLUME (in the teflon) and INNER_SURF (on teflon surface)

![image](https://github.com/next-exp/nexus/assets/32701127/2f627b0f-70cb-4810-b69c-cb222e062986)
![image](https://github.com/next-exp/nexus/assets/32701127/21ffc3af-7fe7-438b-b562-6f86e4ef9f3c)
![image](https://github.com/next-exp/nexus/assets/32701127/ed810fc5-6681-453f-b114-989092f98884)

I mark as draft as I don't think the translations or rotations are working and needs speed benchmarking.

2024-02-27 08:38 UTC, paolafer commented
Does this class replace also `HexagonPointSampler`?

2024-02-28 17:18 UTC, kvjmistry commented
The speed improvement is not that different than what is currently done in NEXT-100. So, I will leave that as it is (the volume checker in NEXT-100 code ensures the right region is sampled anyway). Removed the hexagon point sampler in place of this code. 
Ready for review!

2024-03-07 12:49 UTC, paolafer requested changes

2024-03-07 12:49 UTC, paolafer commented on source/utils/PolygonPointSampler.cc
> +        G4double x = rad * cos(phi);
You're declaring the `x` and `y` variables twice here.

2024-03-07 12:49 UTC, paolafer commented on source/utils/PolygonPointSampler.cc
> +    // Center of the chamber
Change this comment (I guess it was just a repetition of the previous one).

2024-03-07 12:49 UTC, paolafer commented on source/utils/PolygonPointSampler.cc
> +    // Generating from inside the cylinder (between min_radius and max_radius)
Same here (maybe cylinder --> polygon?)

2024-03-07 12:49 UTC, paolafer commented on source/utils/PolygonPointSampler.cc
> +        valid_sample= true;
Why do you assign two different values to the same variable in adjacent lines? Wouldn't the second assignment always overcome the first one?

2024-03-07 12:49 UTC, paolafer commented on source/utils/PolygonPointSampler.cc
> +        if (p1[0] == p2[0] || x <= x_intersection) {
I don't understand the comment to the first condition: if `p1` and `p2` are two subsequent vertices of the polygon, the condition of them having the same `x` coordinate doesn't mean that the point is on the same line as the edge, does it? I don't understand the purpose of the `p1[0] == p2[0]` condition. It looks like it's the case where an edge is vertical.

2024-03-07 12:49 UTC, paolafer commented on source/utils/PolygonPointSampler.cc
> +        // Want outside inner and inside outter
Typo: outter --> outer.

2024-03-25 15:28 UTC, kvjmistry commented on source/utils/PolygonPointSampler.cc
> +        G4double x = rad * cos(phi);
fixed

2024-03-25 15:28 UTC, kvjmistry commented on source/utils/PolygonPointSampler.cc
> +    // Center of the chamber
fixed

2024-03-25 15:28 UTC, kvjmistry commented on source/utils/PolygonPointSampler.cc
> +    // Generating from inside the cylinder (between min_radius and max_radius)
fixed

2024-03-25 15:30 UTC, kvjmistry commented on source/utils/PolygonPointSampler.cc
> +        valid_sample= true;
fixed

2024-03-25 15:30 UTC, kvjmistry commented on source/utils/PolygonPointSampler.cc
> +        if (p1[0] == p2[0] || x <= x_intersection) {
removed that condition, didnt seem to do anything

2024-03-25 15:30 UTC, kvjmistry commented on source/utils/PolygonPointSampler.cc
> +        // Want outside inner and inside outter
fixed

2024-03-27 11:01 UTC, paolafer commented on source/geometries/Next1EL.cc
> +  active_gen_ = new PolygonPointSampler(active_diam_/2.,active_diam_/2. + ltube_diam_/2. + tpb_thickn_, active_length_, 6, nullptr, active_position_);
I think that there's something wrong in the value of the maximum radius in this case: `ltube_diam_` has the same value as `active_diam_`.

2024-04-03 14:58 UTC, kvjmistry commented on source/geometries/Next1EL.cc
> +  active_gen_ = new PolygonPointSampler(active_diam_/2.,active_diam_/2. + ltube_diam_/2. + tpb_thickn_, active_length_, 6, nullptr, active_position_);
Sorry, I didn't see this comment till you mentioned it today, fixed it now!

2024-04-04 11:04 UTC, paolafer approved these changes
Nice generalization for a polygon point sampler! Approved!

2024-04-04 11:04 UTC, merged