DEMO++ energy plane
next-exp/nexus pull request #32
Opened 2020-09-16 10:42 UTC by paolafer

This PR fixes the dimensions and relative distances of the DEMO++ energy plane. 
A copper ring is added to the sapphire windows and the flanges are removed, since they are not relevant for the optical response of the detector.
A number of cosmetic changes are also implemented, following the current coding conventions.

2020-09-29 09:07 UTC, jmalbos requested changes

2020-09-29 09:07 UTC, jmalbos commented on source/geometries/NextDemoEnergyPlane.cc
> +// Energy plane geometry of the DEMO++ detector.
Geometry of the DEMO++ energy plane.

2020-09-29 09:07 UTC, jmalbos commented on source/geometries/NextDemoEnergyPlane.cc
>    using namespace CLHEP;
You probably don't need this.

2020-09-29 09:07 UTC, jmalbos commented on source/geometries/NextDemoEnergyPlane.h
> +// Energy plane geometry of the DEMO++ detector.
Geometry of the DEMO++ energy plane.

2020-09-29 09:07 UTC, jmalbos commented on source/geometries/NextDemoEnergyPlane.cc
>        G4cout << "\n\nERROR: Number of PMTs doesn't match with number of positions calculated\n";
Replace this with a `G4Exception`.

2020-09-29 09:07 UTC, jmalbos commented on source/geometries/NextDemoEnergyPlane.cc
>      pmt_ = new PmtR11410();
I don't think you need this object to be dynamically created here and kept around till the destructor is called. You could simply do
`PmtR11410 pmt();`
in the function where it is used, and let the scope take care of its destruction.

2020-09-29 13:06 UTC, paolafer commented on source/geometries/NextDemoEnergyPlane.cc
> +// Energy plane geometry of the DEMO++ detector.
Done.

2020-09-29 13:06 UTC, paolafer commented on source/geometries/NextDemoEnergyPlane.cc
>    using namespace CLHEP;
Removed.

2020-09-29 13:07 UTC, paolafer commented on source/geometries/NextDemoEnergyPlane.cc
>        G4cout << "\n\nERROR: Number of PMTs doesn't match with number of positions calculated\n";
Replaced.

2020-09-29 13:09 UTC, paolafer commented on source/geometries/NextDemoEnergyPlane.cc
>      pmt_ = new PmtR11410();
PmtR11410 needs to be instantiated in the constructor, because it has configuration parameters set via messenger.

2020-09-29 13:09 UTC, paolafer commented on source/geometries/NextDemoEnergyPlane.h
> +// Energy plane geometry of the DEMO++ detector.
Done.

2020-10-26 14:36 UTC, jmunozv commented
Optical surfaces must be added to PEDOT and TPB coating layers

2020-10-26 15:28 UTC, jmunozv approved these changes
I approve this first version of DEMO++ Energy Plane

2020-10-26 15:48 UTC, jmalbos approved these changes

2020-10-26 15:49 UTC, merged