Pet box geometry
next-exp/nexus pull request #33
Opened 2020-09-24 09:42 UTC by carmenromo

This PR adds the current geometry of the pet box, the first PETALO prototype, with the three types of sensors that will be used in the detector.

2020-09-24 11:17 UTC, paolafer requested changes
Remove from the PR the `source/.DS_Store` file.

2020-09-24 11:20 UTC, paolafer requested changes
Also, change from `true` to `false` the variables responsible of the overlapping. We don't want to print overlap messages once the code is approved.

2020-09-24 12:54 UTC, paolafer requested changes
A test should be added to `produce_output_test` and `sensitive_detectors_test` with the new geometry.

2020-09-24 13:19 UTC, carmenromo commented
> A test should be added to `produce_output_test` and `sensitive_detectors_test` with the new geometry.

right!

2020-09-24 17:20 UTC, carmenromo commented
> Remove from the PR the `source/.DS_Store` file.

Done!

2020-09-24 17:20 UTC, carmenromo commented
> Also, change from `true` to `false` the variables responsible of the overlapping. We don't want to print overlap messages once the code is approved.

Done!

2020-09-28 15:33 UTC, paolafer requested changes
I still find a misalignment of volumes in the VUV tile of Hamamatsu. A particle travelling from the centre goes first through `ACTIVE_LXE_TILE`, then through `TILE_QUARTZ_WINDOW ` and finally through `ACTIVE_LXE_TILE` again (see attached screenshot).

<img width="853" alt="Screenshot 2020-09-28 at 17 31 20" src="https://user-images.githubusercontent.com/8114436/94453143-a5a72a80-01b0-11eb-9a58-692cfe74810d.png">

2020-09-28 15:33 UTC, paolafer commented on source/geometries/PetBox.cc
> +    G4double air_source_tube_len = source_tube_length_/2.-source_tube_thickness_;
It is better to be consistent throughout the code and use `length` variables as lenghts (not half lengths) and in G4Tubs use `length/2`. If we do it always the same way it's easier to check that things are corrects.

2020-09-30 13:28 UTC, paolafer requested changes

2020-09-30 13:28 UTC, paolafer commented on source/geometries/TileHamamatsuVUV.cc
> +        G4String vol_name = "SiPMHmstuVUV_" + std::to_string(copy_no);
It's fine to shorten the name, but let's keep the order of the letters (from Hamamatsu it should be `Hmtsu`, not `Hmstu`).

2020-09-30 13:28 UTC, paolafer commented on source/geometries/SiPMpetBlue.cc
> +// nexus | SiPMpetBlue.cc
Why don't you call this class also SiPMHamamatsuBlue, following the same convention as the other two?

2020-09-30 13:28 UTC, paolafer commented on source/geometries/PetBox.h
> +#ifndef PET_BOX_H_
Drop the trailing underscore, following the [convention rules](https://github.com/next-exp/nexus/wiki/Coding-conventions-and-style-guide).

2020-10-02 08:16 UTC, carmenromo commented on source/geometries/TileHamamatsuVUV.cc
> +        G4String vol_name = "SiPMHmstuVUV_" + std::to_string(copy_no);
Ups you are right

2020-10-15 14:34 UTC, paolafer requested changes

2020-10-15 14:34 UTC, paolafer commented on source/geometries/SiPMFBKVUV.cc
> +      G4cout << "Box geom in SIPMFBK!: " << box_geom_ << G4endl;
Remove comment.

2020-10-15 14:34 UTC, paolafer commented on source/geometries/SiPMHamamatsuVUV.cc
> +    G4GenericMessenger::Command& time_cmd =
Since the tiles are not instantiated in the `PetBox` constructor anymore, we cannot use configuration parameters in the tile and SiPM classes anymore. If you add to your macro, for instance, `/Geometry/SiPMpet/time_binning 2. microsecond`, the job crashes because that command has not been registered in construction.

Everything needs to be set through `setters` methods, and the parameters need to appear in the `PetBox` class. Review all the tile and SiPM classes about this.

2020-10-15 14:34 UTC, paolafer commented on source/geometries/PetBox.cc
> +      box_geom_ = 1;
I would put all the variables that depend on the type of tile here, so they're in the same place and one can see in one glance what's the difference between the configurations. Also, this way you can avoid another `if else` clause below. So, just make `dist_dice_flange` a global variable and move it here.

2020-10-15 14:34 UTC, paolafer commented on source/geometries/PetBox.cc
> +      x_pos_ = ih_x_size_/2. + dist_ihat_panel_ + panel_thickness_ + active_depth_ + tile_thickn_/2.;
I think that the `x_pos_` variable doesn't need to be global. As a general rule, if a variable is used only in one scope, make it local: global variables are needed when they have to be used in more than one scope.

2020-10-15 14:34 UTC, paolafer commented on source/geometries/PetBox.cc
> +    if (tile_type_ == "HamamatsuVUV") {
I would write `x_pos` for this case with the same structure as the other two tiles; just place a placeholder with a reasonable value (let's say, 20 mm), till we know the exact distance. Also add a comment in the code to remind us that we need to update that number.

2020-10-15 14:34 UTC, paolafer commented on source/geometries/PetBox.cc
> +    // Aliminum cylinder
Typo: aliminum --> aluminum.

2020-10-16 11:24 UTC, paolafer requested changes

2020-10-16 11:24 UTC, paolafer commented on source/geometries/PetBox.cc
> +    G4Material* vacuum = G4NistManager::Instance()->FindOrBuildMaterial("G4_Galactic");;
Remove one semicolon.

2020-10-16 11:24 UTC, paolafer commented on source/geometries/PetBox.cc
> +    G4double lat_panel_xpos = entry_panel_xpos + dist_entry_panel_lat_panel_ + lat_panel_width_/2.;
I think that `+ panel_thickness_/2.` is missing in the `lat_panel_xpos` variable.

2020-10-16 11:24 UTC, paolafer commented on source/geometries/PetBox.cc
> +    G4double low_lat_panel_xpos = entry_panel_xpos + dist_entry_panel_lat_panel_ +
I think that `+ panel_thickness_/2.` is missing in the `low_lat_panel_xpos` variable.

2020-10-16 11:24 UTC, paolafer commented on source/geometries/PetBox.cc
> +                    dist_entry_panel_lat_panel_(1.45*mm),
For variables that are a bit tricky, and have not self-evident names, it is useful to add a comment with `//`, so that in the future we don't get crazy remembering what they were. For instance I would add a comment for `dist_entry_panel_lat_panel_` such as **x distance between the internal surface of the entry panel and the edge of the lateral panel**.

2020-10-16 11:24 UTC, paolafer commented on source/geometries/PetBox.cc
> +                    dist_ihat_panel_(2.*mm),
I would add a comment also here: **x distance between the internal surface of the hat and the external surface of the entry panel**.

2020-10-16 12:31 UTC, paolafer requested changes

2020-10-16 12:31 UTC, paolafer commented on source/geometries/TileHamamatsuBlue.cc
> +    G4int sensor_depth = 1;
You can write directly `1` and `2` in the setters below; the code is well readable, since the setter methods describe what they're doing in the name

2020-10-16 12:31 UTC, paolafer commented on source/geometries/TileHamamatsuBlue.cc
> +  {
In this tile we have to add also a layer of wavelength shifter. You can add it made of TPB, for the moment, when we decide which material to use we'll refine the simulation. The thickness can be 1 micrometer, as in NEXT.

2020-10-16 12:31 UTC, paolafer commented on source/geometries/SiPMHamamatsuBlue.cc
> +    G4Box* epoxy_solid =
Move the epoxy layer to the tile class.

2020-10-16 12:31 UTC, paolafer commented on source/geometries/PetBox.cc
> +    G4Box* active_solid =
The active dimensions should be exactly the dimensions of the LXe enclosed in the panels and between the surface of the tiles and the wall of the internal hat. We should write the code in such a way that the x dimension of ACTIVE depends on the particular `dist_dice_flange` of each tile.

2020-10-17 20:20 UTC, paolafer requested changes

2020-10-17 20:20 UTC, paolafer commented on source/geometries/SiPMHamamatsuVUV.cc
> +        sipmsd->SetDetectorNamingOrder(naming_order_);
Initialize `naming_order` and `mother_depth` to `0` and `sensor_depth` to `-1` in the initialization list. We should also add a check before `sipmsd->SetDetectorVolumeDepth(sensor_depth_);` to ensure that `sensor_depth_` is different than `-1`, since we always need to set that variable. However, mother_depth and naiming_order can be left to the default. The `box_geom_` variable needs also to be initialized. 

Do it in the 3 SiPM classes.

2020-10-19 14:20 UTC, carmenromo commented on source/geometries/SiPMHamamatsuVUV.cc
> +    G4GenericMessenger::Command& time_cmd =
I see what you mean, but is it worthy to remove all the conf parameters of these classes? At the end, this is a very concrete case, and if we want to use the SiPM classes for instance in another geometry, we will not be able to use them as in other geometries we have...

2020-10-19 14:24 UTC, paolafer commented on source/geometries/SiPMHamamatsuVUV.cc
> +    G4GenericMessenger::Command& time_cmd =
The problem is that the code as it is now crashes, if you use one of those configuration parameters, and we need to fix it. Either we eliminate the possibility of changing the values of those parameters (which I don't like), or we use setters. I don't see a third option, do you?

2020-10-19 14:25 UTC, paolafer commented on source/geometries/SiPMHamamatsuVUV.cc
> +    G4GenericMessenger::Command& time_cmd =
You will need to use setters in other geometries as well, of course.

2020-10-19 14:38 UTC, carmenromo commented on source/geometries/PetBox.cc
> +      x_pos_ = ih_x_size_/2. + dist_ihat_panel_ + panel_thickness_ + active_depth_ + tile_thickn_/2.;
But in our case, x_pos_ depends on the tile we are using, should it be local too?

2020-10-19 14:38 UTC, carmenromo commented on source/geometries/PetBox.cc
> +    if (tile_type_ == "HamamatsuVUV") {
Oh, I see, this is the answer for my previous question 👍

2020-10-19 15:44 UTC, carmenromo commented on source/geometries/PetBox.cc
> +    G4double lat_panel_xpos = entry_panel_xpos + dist_entry_panel_lat_panel_ + lat_panel_width_/2.;
You are right

2020-10-19 16:04 UTC, carmenromo commented on source/geometries/TileHamamatsuBlue.cc
> +  {
You are right, I forgot!

2020-10-19 16:05 UTC, carmenromo commented on source/geometries/SiPMHamamatsuVUV.cc
> +    G4GenericMessenger::Command& time_cmd =
Ok, I see, done!

2020-10-20 14:08 UTC, paolafer commented
More things: tests should be added to check the correct functioning of sensors, the same kind as those for the full body or the old tile geometry.

2020-10-21 10:37 UTC, paolafer requested changes

2020-10-21 10:37 UTC, paolafer commented on source/sensdet/ToFSD.h
> +    G4int box_geom_; ///< Boolean required to change the naming_order_ for the case of the BoxSetup
This variable needs to be initialized in the `.cc` file.

2020-10-21 10:37 UTC, paolafer commented on source/sensdet/ToFSD.cc
> +    if (box_geom_==1) { // Hamamatsu
The last `else` makes irrelevant the `if (naming_order_ != 0)` clause.
I would do the following:

```
G4int pmtid = touchable->GetCopyNumber(sensor_depth_);
if (naming_order_ != 0) {
    G4int motherid = touchable->GetCopyNumber(mother_depth_);
    pmtid = naming_order_*motherid + pmtid;
}

if (box_geom_==1) { // Hamamatsu
      std::vector<G4int> init_ids ({ 0, 4, 32, 36, 64, 68, 96, 100 });
      G4int motherid = touchable->GetCopyNumber(mother_depth_);
      G4int first_id = (init_ids)[motherid];
      pmtid = first_id + pmtid;
} else if (box_geom_==2) { // FBK
      std::vector<G4int> init_ids ({ 0, 8, 128, 136, 256, 264, 384, 392 });
      G4int motherid = touchable->GetCopyNumber(mother_depth_);
      G4int first_id = (init_ids)[motherid];
      pmtid = first_id + pmtid;
}

return pmtid;
```

2020-10-21 10:52 UTC, carmenromo commented on source/sensdet/ToFSD.cc
> +    if (box_geom_==1) { // Hamamatsu
Done!

2020-10-21 15:00 UTC, carmenromo commented on source/geometries/SiPMHamamatsuBlue.cc
> +    G4Box* epoxy_solid =
Done!

2020-10-23 15:49 UTC, carmenromo commented on source/geometries/PetBox.cc
> +    G4Box* active_solid =
Done!

2020-11-09 11:44 UTC, paolafer commented on source/geometries/TileHamamatsuBlue.cc
> +    new G4PVPlacement(0, G4ThreeVector(0., 0., tile_z_/2. - wls_depth_/2.),
Be careful! You're placing the wavelengthshifting layer on top of the epoxy layer!

2020-11-09 11:46 UTC, paolafer commented on source/geometries/PetBox.cc
> +    new G4PVPlacement(0, G4ThreeVector(-active_x_pos, 0., 0.), active_logic,
There's an overlap warning between ACTIVE and TILE_7. When you add a new volume, or modify an existing one, always make sure that no overlaps are generated.

2020-11-13 12:56 UTC, carmenromo commented on source/geometries/TileHamamatsuBlue.cc
> +    new G4PVPlacement(0, G4ThreeVector(0., 0., tile_z_/2. - wls_depth_/2.),
You are right! But the order coming from outside is: wavelength shifter, epoxy and then tile, right?
So for the wavelength shifter the placement is correct but no the epoxy one, isn't it?

2020-11-13 13:00 UTC, carmenromo commented on source/geometries/PetBox.cc
> +    new G4PVPlacement(0, G4ThreeVector(-active_x_pos, 0., 0.), active_logic,
I don't have this overlap... Which tile are you using?

2020-11-13 16:13 UTC, paolafer commented on source/geometries/TileHamamatsuBlue.cc
> +    new G4PVPlacement(0, G4ThreeVector(0., 0., tile_z_/2. - wls_depth_/2.),
Yes, that's the correct order. You have to put the epoxy behind the wavelength shifter.

2020-11-13 16:14 UTC, paolafer commented on source/geometries/PetBox.cc
> +    new G4PVPlacement(0, G4ThreeVector(-active_x_pos, 0., 0.), active_logic,
HamamatsuBlue.

2020-11-20 16:44 UTC, paolafer commented
Tests are failing because you modified the `conftest` file without adding the corresponding test. Please, fix it.

2020-11-20 16:47 UTC, paolafer commented
In fact, I think we should have one test for each configuration of the box, so 3 tests.

2020-11-20 16:55 UTC, paolafer commented on source/geometries/TileHamamatsuBlue.cc
> +    SetDimensions(G4ThreeVector(tile_x_, tile_y_, tile_z_+epoxy_depth_+wls_depth_));
If you make the thickness of the volume tile a bit larger so that the effective tile thickness remain the same, you have to use this total thickness also in the placement of the epoxy and the wavelength shifter.
For instance, the wavelength shifting should be placed as in the following:

`new G4PVPlacement(0, G4ThreeVector(0., 0., (tile_z_+epoxy_depth_+wls_depth_)/2. - wls_depth_/2.)`

2020-11-20 18:12 UTC, carmenromo commented
> In fact, I think we should have one test for each configuration of the box, so 3 tests.

Yeah, absolutely, this was my idea too, but I found some problems and I left the problem there... I have to finish them.

2020-11-20 19:17 UTC, carmenromo commented on source/geometries/TileHamamatsuBlue.cc
> +    SetDimensions(G4ThreeVector(tile_x_, tile_y_, tile_z_+epoxy_depth_+wls_depth_));
You are right!

2020-12-29 16:43 UTC, paolafer reviewed
Have you already modified the panels according to the new drawings?

2020-12-29 16:43 UTC, paolafer commented on source/geometries/TileHamamatsuVUV.h
> +    G4GenericMessenger* msg_;
This variable is unused, please, delete it.

2021-01-04 12:38 UTC, carmenromo commented on source/geometries/TileHamamatsuVUV.h
> +    G4GenericMessenger* msg_;
oh, I just saw this. I'll do it

2021-01-04 12:40 UTC, carmenromo commented
> Have you already modified the panels according to the new drawings?

Yes!

2021-01-05 09:28 UTC, paolafer commented
Reading the full geometry together, I realized that we use the `x` and `y` coordinates in the natural way for the tile geometries (the positions of the SiPMs), while in the box geometry we use `z` and `y` instead. I think this could lead to a lot of headaches, later, because in the database the SiPM positions will probably be `x` and `y`. I think it is better to change it now, simply placing the arrays of SiPMs along z instead of along x, what do you think? Would this change have any implications I'm not seeing?

2021-01-05 19:13 UTC, carmenromo commented
> Reading the full geometry together, I realized that we use the `x` and `y` coordinates in the natural way for the tile geometries (the positions of the SiPMs), while in the box geometry we use `z` and `y` instead. I think this could lead to a lot of headaches, later, because in the database the SiPM positions will probably be `x` and `y`. I think it is better to change it now, simply placing the arrays of SiPMs along z instead of along x, what do you think? Would this change have any implications I'm not seeing?

Yes, I think you are right... And don't you think it would be clearer if we change the pet box geometry instead of the sensors? It is more work but not so difficult I think, and maybe it's worthy. What do you think?

2021-01-05 19:20 UTC, paolafer commented
> > Reading the full geometry together, I realized that we use the `x` and `y` coordinates in the natural way for the tile geometries (the positions of the SiPMs), while in the box geometry we use `z` and `y` instead. I think this could lead to a lot of headaches, later, because in the database the SiPM positions will probably be `x` and `y`. I think it is better to change it now, simply placing the arrays of SiPMs along z instead of along x, what do you think? Would this change have any implications I'm not seeing?
> 
> Yes, I think you are right... And don't you think it would be clearer if we change the pet box geometry instead of the sensors? It is more work but not so difficult I think, and maybe it's worthy. What do you think?

Yes, I wouldn't touch the tile geometry, simply placing the tiles along z instead of along x (which is what you mean with changing the pet box geometry, I understand). The box is a cube, so it is irrelevant if we put the tiles in (0, 0, +/-z) or in (+/-x, 0, 0). The other things to change are the hat, which is not symmetric and should be changed accordingly, and the position of the panels.

2021-01-05 19:24 UTC, paolafer commented on source/geometries/PetBox.cc
> +      new G4PVPlacement(0, G4ThreeVector(wls_xpos, 0., 0.), wls_logic,
You forgot to add the wavelength shifter to the second panel.

2021-01-05 19:34 UTC, paolafer commented on source/geometries/PetBox.cc
> +      new G4PVPlacement(0, G4ThreeVector(wls_xpos, 0., 0.), wls_logic,
In fact, if you place the wavelength shifter inside the panel, instead of in the LXe, you save a line of code (only 1 placement instead of 2).

2021-01-06 22:29 UTC, paolafer commented on source/geometries/PetBox.cc
> +      new G4PVPlacement(0, G4ThreeVector(wls_xpos, 0., 0.), wls_logic,
In the case of the Hamamatsu blue-sensitive SiPMs we need to simulate the panels in a different way, because they are transparent to the optical photons in that range of wavelengths (this is why we can put them in front of the SiPMs). We can think about it later and focus on finishing this PR for the other two configurations.

2021-01-14 10:26 UTC, paolafer commented
@carmenromo, can you rebase this branch on upstream/petalo? There are some modifications there that affect test files. You'll probably have to solve conflicts.

2021-01-14 10:33 UTC, carmenromo commented
> @carmenromo, can you rebase this branch on upstream/petalo? There are some modifications there that affect test files. You'll probably have to solve conflicts.

Sure! I'll do it

2021-01-18 07:30 UTC, paolafer commented
Persistency tests are failing for me after these last commits, with `FileNotFoundError`. Are they for you?

2021-01-18 09:31 UTC, carmenromo commented
> Persistency tests are failing for me after these last commits, with `FileNotFoundError`. Are they for you?

You are right, I thought I did check them... I'll fix it!

2021-01-18 09:51 UTC, carmenromo commented
> Persistency tests are failing for me after these last commits, with `FileNotFoundError`. Are they for you?

Fixed! There was an extra `.h5` term in the macros for the pet box cases.

2021-01-18 10:14 UTC, paolafer approved these changes
This PR adds the geometry of the first PETALO set-up (a.k.a. _cajita_) to nexus. The case with wavelength shifter needs further development, but the geometry is ready to be used with VUV-sensitive SiPMs. It has been a huge work, following the always evolving technical drawings and our own understanding of the simulation. Congratulations @carmenromo!

2021-01-18 10:15 UTC, merged