Demo tp
next-exp/nexus pull request #35
Opened 2020-10-14 14:59 UTC by jmunozv

First version of DEMO++ TrackingPlane implementing both the "original" one, and the "type1" currently in use.
The two types of TrackingPlane are selectable by parameter.
Both of them make use of the new NextDemoSiPMBoard.

2020-10-19 14:48 UTC, paolafer requested changes

2020-10-19 14:48 UTC, paolafer commented on source/geometries/NextDemoSiPMBoard.cc
> +                    mask_name, board_logic, false, 0, true);
Before approving this PR, please set to false all the overlap checks.

2020-10-19 14:48 UTC, paolafer commented on source/geometries/NextDemoTrackingPlane1.cc
> +  /// Verbosity
Remove comments or uncomment.

2020-10-20 10:53 UTC, jmunozv commented on source/geometries/NextDemoTrackingPlane1.cc
> +  /// Verbosity
Done

2020-10-27 16:14 UTC, paolafer commented
The variable `gate_tp_copper_distance_` is not used in NextDemoInnerElements, please remove it.

2020-10-27 16:38 UTC, jmunozv commented
> The variable `gate_tp_copper_distance_` is not used in NextDemoInnerElements, please remove it.

Done

2020-10-27 22:38 UTC, jmalbos commented on source/geometries/NextNewKDB.cc
This change in a NEW file shouldn't have been committed.

2020-10-28 07:47 UTC, jmunozv commented on source/geometries/NextNewKDB.cc
My mistake. Sorry.

2020-10-29 14:06 UTC, paolafer approved these changes
The geometry looks fine, I'm going to approve this PR.

2020-10-29 14:06 UTC, merged