DEMO++ field cage
next-exp/nexus pull request #37
Opened 2020-10-20 11:02 UTC by paolafer

This PR reviews the geometry of the DEMO++ field cage and updates it to the latest drawings.

2020-10-26 14:54 UTC, jmunozv requested changes

2020-10-26 14:54 UTC, jmunozv commented on source/geometries/NextDemoFieldCage.h
>      const G4double ltube_thickn_;
You are using two different names to refer to the same volume: "ltube_XXXX" and "light_tube_XXXX".
Please select just one.

2020-10-26 14:54 UTC, jmunozv commented on source/geometries/NextDemoFieldCage.cc
> +      G4Tubs* anode_quartz_solid =
You have implemented the quartz volume, but not  ITO and TPB coatings.

2020-10-26 14:54 UTC, jmunozv commented on source/geometries/NextDemoFieldCage.cc
> +    bar_end_z_ (403.5 * mm),
I have a value of 413.5 mm for this dimension in my notes. Could you please check it ??

2020-10-26 15:31 UTC, paolafer commented on source/geometries/NextDemoFieldCage.h
>      const G4double ltube_thickn_;
Done.

2020-10-26 16:07 UTC, paolafer commented on source/geometries/NextDemoFieldCage.cc
> +      G4Tubs* anode_quartz_solid =
Done.

2020-10-27 07:47 UTC, jmunozv commented
I approve this first version of NextDEMO Field Cage

2020-10-27 07:50 UTC, jmunozv approved these changes

2020-10-27 07:51 UTC, merged