DEMO++ Geometry — Pressure Vessel and Main Class
next-exp/nexus pull request #44
Opened 2020-10-31 09:18 UTC by jmalbos

This PR overhauls the main class of the DEMO++ geometry and updates the description of the detector's pressure vessel.

2020-11-02 10:04 UTC, jmunozv approved these changes
Sorry. This comment was for another PR.

Current one is still pending of review.

2020-11-02 11:00 UTC, jmunozv commented
Current implementation does not allow to set by parameter the pressure of the gas, and it must.

NextDemo::GenerateVector(...) must be implemented.

CATHODE_GRID & VESSEL overlap.

2020-11-11 15:26 UTC, jmunozv commented on source/geometries/NextDemoInnerElements.h
> +// Geometry
Complete. Here and in .cc

2020-11-11 15:31 UTC, jmunozv commented on source/geometries/NextDemo.cc
> +  G4VPhysicalVolume* vessel_phys_vol =
This variable is not needed

2020-11-11 15:37 UTC, jmunozv commented on source/geometries/NextDemoVessel.cc
> +  gas_pressure_(15.*bar),
I think it is better to set a default value closer to reality (8.30 for instance). I think the maximum pressure that DEMO vessel can hold is 10 bar.

2020-11-11 15:43 UTC, jmunozv commented on source/geometries/NextDemo.cc
> +  inner_geom_->SetMotherPhysicalVolume(vessel_geom_->GetGasPhysicalVolume());
I think it makes little sense to have `SetMotherPhysicalVolume ` and `SetMotherLogicalVolume ` for the same class. The "Physical" method should be enough and than get the LogicalVolume directly in the class.

Anyway I think this situation occurs in many places, so may be we could fix it in a dedicated PR devoted to this.

2020-11-11 15:55 UTC, jmunozv commented on source/geometries/NextDemo.cc
> +  return G4ThreeVector();
You forgot to implement it.

2020-11-11 16:03 UTC, jmunozv commented on source/geometries/NextDemoVessel.cc
> +  sc_yield_cmd.SetUnitCategory("1/Energy");
Define the unit "1/Energy" first.

2020-11-11 16:05 UTC, jmunozv requested changes
In addition to single comments, you need to:

- Fix the overlap between VESSEL & GAS
- Modify macro files according to new implementation.
- Modify tests according to new implementation.

2020-11-11 17:54 UTC, jmalbos commented on source/geometries/NextDemo.cc
> +  inner_geom_->SetMotherPhysicalVolume(vessel_geom_->GetGasPhysicalVolume());
I agree, but I have tried to modify as little as possible the existing classes in this PR. As you suggest, this should be addressed in a separate one.

2020-11-11 21:35 UTC, jmalbos commented
All comments have been addressed. Tests and macros do not require any change, as far as I can see.

2020-11-12 11:19 UTC, jmunozv commented
Add VESSEL visibility and verbosity parameters and use them accordingly, in the same way than in the rest of the geometry sub-systems.

There are some "persistency" and "sensitive detector" tests failing. 

The Vertex generators from ACTIVE and TP_PLATE have stopped working.

2020-11-19 15:30 UTC, jmalbos commented
The recent commits fix the issues with the failing tests. It was all connected with the relative position of the vessel with respect to the origin of coordinates.

2020-11-19 17:40 UTC, jmalbos commented
> Add VESSEL visibility and verbosity parameters and use them accordingly, in the same way than in the rest of the geometry sub-systems.

Done.

2020-11-20 16:09 UTC, jmunozv commented
> > Add VESSEL visibility and verbosity parameters and use them accordingly, in the same way than in the rest of the geometry sub-systems.
> 
> Done.

The verbosity has not been added but I guess it is not strictly necessary.

2020-11-20 16:11 UTC, jmunozv approved these changes
This PR implements a simplified version of DEMOpp vessel and main class which is more than enough by the moment.

Tests run succesfully.

I approve this PR.

2020-11-20 16:30 UTC, paolafer commented on source/geometries/NextDemo.cc
> +  else if (region == "CALIBRATION_SOURCE") {
Is this vertex given in absolute coordinates as well as the `AD_HOC` one? If I understand correctly from the `NextDemoVessel::GenerateVertex()` method, it is not, therefore it should be also displaced, is that correct?

2020-11-20 23:14 UTC, jmalbos commented on source/geometries/NextDemo.cc
> +  else if (region == "CALIBRATION_SOURCE") {
You're right. Fixed!

2020-11-23 10:19 UTC, paolafer requested changes

2020-11-23 10:19 UTC, paolafer commented on source/geometries/NextDemoVessel.cc
> +    msg_->DeclareProperty("calsrc_position", calsrc_position_,
Is this parameter the z position? I would add it explicitly in the comment, and also add the unit category of length, to avoid errors.

2020-11-23 10:19 UTC, paolafer commented on source/geometries/NextDemoVessel.cc
> +    msg_->DeclareProperty("calsrc_angle", calsrc_angle_,
Is it possible to add a unit category for the angle? I tried to use `45 deg` and it was not recognized. Otherwise we have to state explicitly in the comment that the value must be in radians.

2020-11-23 22:44 UTC, jmalbos commented
> Is this parameter the z position? I would add it explicitly in the comment, and also add the unit category of length, to avoid errors. 

I've changed the name of the parameter to `calsrc_zpos`, amended the comment and added the unit category.

2020-11-23 22:45 UTC, jmalbos commented
> Is it possible to add a unit category for the angle? I tried to use `45 deg` and it was not recognized. Otherwise we have to state explicitly in the comment that the value must be in radians. 

I've added the unit following the example B5.

2020-11-24 13:24 UTC, paolafer approved these changes
I have no further comments to make, and consider this PR approved.

2020-11-24 13:24 UTC, merged