Add new generator SingleParticleAngle.
next-exp/nexus pull request #50
Opened 2020-11-16 13:07 UTC by MiryamMV

Add a new generator (already implemented in PETALO) which allows to define a solid angle for the momentum of the particle.

2020-11-16 14:10 UTC, jmalbos commented
I think it would be better to integrate this feature in the `SingleParticleGenerator` rather than creating a new generator that is 95% identical.

2020-11-16 14:11 UTC, paolafer commented
> I think it would be better to integrate this feature in the `SingleParticleGenerator` rather than creating a new generator that is 95% identical.

I agree.

2020-11-16 15:48 UTC, paolafer commented on CMakeLists.txt
> +#IF(COMMAND cmake_policy)
Why do you need to comment this? I remember these lines were added to deal with different versions of cmake.

2020-11-16 15:55 UTC, MiryamMV commented on CMakeLists.txt
> +#IF(COMMAND cmake_policy)
It gives me errors while compiling if I don't comment it. Should I reverse that change for the PR?

2020-11-16 15:57 UTC, paolafer commented on CMakeLists.txt
> +#IF(COMMAND cmake_policy)
I think we should understand why you get errors now and before you didn't. It should not depend on the new class you added.

2020-11-16 16:01 UTC, MiryamMV commented on CMakeLists.txt
> +#IF(COMMAND cmake_policy)
It always gives me errors when I'm in local. I just commited it to be able to switch branch, nothing to do with the new class.

2020-11-16 16:03 UTC, paolafer commented on CMakeLists.txt
> +#IF(COMMAND cmake_policy)
You should remove it from the PR, otherwise this change will get included when we approve it. On the other hand, we can investigate why you get this error in your local repository.

2020-11-27 08:35 UTC, paolafer commented on source/base/GeneratorFactory.cc
> +#include "SingleParticleAngle.h"
Remove this include, since it's no longer necessary and this class doesn't exist.

2020-11-27 08:35 UTC, paolafer commented on source/base/GeneratorFactory.cc
> +  else if (name_ == "SINGLE_PARTICLE_ANG") p = new SingleParticleAngle();
Same as above.

2020-11-27 08:37 UTC, paolafer commented
With this new feature, the `SingleParticle2PiGenerator` class becomes obsolete. I would delete it and add the exact values that correspond to a forward generation from the DEMO vessel sideport as a comment.

2020-11-27 10:49 UTC, paolafer commented
It would be also very useful to add a test that checks that the randomly produced direction is indeed within the specified range. In order to do that in a simple way, within the `catch2` framework, you will first need to extract the code that generates the direction as an individual function (in a similar way to the already existing `RandomEnergy()` function) and then use that function in a test, such as that in `source/tests/utils/BoxPointSamplerTests.cc`. We should create a new file, called RandomUtils, where these functions could live, in such a way that they can be used anywhere in the code. We can talk on zoom, if you need any explanation on how to do that.

2020-12-29 15:07 UTC, paolafer requested changes

2020-12-29 15:07 UTC, paolafer commented on source/utils/RandomUtils.h
> +// nexus | Visibilities.h
Please, change the brief description of the class, accordingly.

2020-12-29 15:07 UTC, paolafer commented on source/generators/SingleParticleGenerator.cc
> +//G4double SingleParticleGenerator::RandomEnergy() const
Delete commented lines, since they are not used anymore.

2020-12-29 15:07 UTC, paolafer commented on source/generators/SingleParticleGenerator.cc
> +    px = p.x();
This way, you always get a momentum with module equal to 1. You need to multiply `p.x()`, `p.y()` and `p.z()` by `pmod`, right?

2020-12-29 15:07 UTC, paolafer commented on source/utils/RandomUtils.h
> +	    dir = true;
Since the function returns immediately after, there is no need of setting the `dir` variable to `true`.

2020-12-29 15:13 UTC, paolafer commented
The test is still missing.

2021-01-19 13:48 UTC, paolafer commented on source/tests/utils/RandomUtilsTest.cc
> +      x = costheta_max;
Have you considered using the std::swap function to perform this operation?

2021-01-19 16:35 UTC, paolafer commented on source/tests/utils/RandomUtilsTest.cc
> +TEST_CASE("Direction Function") {
This test is failing for me, I attach the error message.

<img width="426" alt="Screenshot 2021-01-19 at 17 34 49" src="https://user-images.githubusercontent.com/8114436/105064028-b12ea200-5a7c-11eb-98fa-415d85522f23.png">

2021-01-26 12:30 UTC, merged